#!/usr/bin/env python3
"""Generates src/notes.c : Game Boy pitch tables indexed by ORCA note number.

ORCA gives us (octave, note) -> n = octave*12 + note, 0..127.  We keep 0..95.

  pulse/wave channels: f = 131072 / (2048 - x)      ->  x = 2048 - 131072/f
  the wave channel runs an octave lower for the same x, so the driver
  recomputes  x3 = 2048 - (2048 - x)/2  at runtime.

  noise channel: f = 262144 / (r * 2^(s+1)), r==0 treated as 0.5
"""
import math
import sys

N = 128


def pulse_table():
    out = []
    for n in range(N):
        f = 440.0 * 2.0 ** ((n - 69) / 12.0)
        # Transpose up until the divider fits the 11-bit register.
        while f > 0 and 131072.0 / f > 2047.0:
            f *= 2.0
        x = int(round(2048.0 - 131072.0 / f))
        out.append(max(0, min(2047, x)))
    return out


def noise_table():
    combos = []
    for s in range(14):          # shift 0..13 (14,15 are silent)
        for r in range(8):
            div = 0.5 if r == 0 else float(r)
            f = 262144.0 / (div * 2 ** (s + 1))
            combos.append((f, (s << 4) | r))
    combos.sort()
    out = []
    for n in range(N):
        f = 440.0 * 2.0 ** ((n - 69) / 12.0)
        best = min(combos, key=lambda c: abs(c[0] - f))
        out.append(best[1])
    return out


def wave_shapes():
    """Eight 32-sample waveforms for CH3, packed two nibbles per byte."""
    shapes = [
        ("TRI", lambda n: n if n < 16 else 31 - n),
        ("SAW", lambda n: n // 2),
        ("SQR", lambda n: 15 if n < 16 else 0),
        ("PUL", lambda n: 15 if n < 8 else 0),
        ("SIN", lambda n: int(round(7.5 + 7.5 * math.sin(2 * math.pi * n / 32)))),
        ("ORG", lambda n: int(round(7.5 + 5.0 * math.sin(2 * math.pi * n / 32)
                                       + 2.5 * math.sin(4 * math.pi * n / 32)))),
        ("RND", lambda n: (n * 7 + (n * n) // 3) % 16),
        ("RMP", lambda n: 15 - n // 2),
    ]
    out = []
    for _, f in shapes:
        samples = [max(0, min(15, f(n))) for n in range(32)]
        out += [(samples[i * 2] << 4) | samples[i * 2 + 1] for i in range(16)]
    return out


def main():
    p, q, w = pulse_table(), noise_table(), wave_shapes()
    with open(sys.argv[1], 'w') as f:
        f.write("/* generated by tools/makenotes.py -- do not edit */\n\n")
        f.write("const unsigned int note_period[%d] = {\n" % N)
        for i in range(0, N, 8):
            f.write("    " + ",".join("%4d" % v for v in p[i:i + 8]) + ",\n")
        f.write("};\n\nconst unsigned char note_noise[%d] = {\n" % N)
        for i in range(0, N, 8):
            f.write("    " + ",".join("0x%02X" % v for v in q[i:i + 8]) + ",\n")
        f.write("};\n\nconst unsigned char wave_shapes[%d] = {\n" % len(w))
        for i in range(0, len(w), 16):
            f.write("    " + ",".join("0x%02X" % v for v in w[i:i + 16]) + ",\n")
        f.write("};\n")
    print("notes: pulse[%d] noise[%d] waves[%d]" % (len(p), len(q), len(w) // 16))


main()
